qcacld-3.0: Drop mac_phy_cap evaulation as true
- This fixes the following warning:

/home/matheus/derp/kernel/oneplus/sm8150/drivers/staging/qcacld-3.0/core/wma/src/wma_main.c: In function 'wma_print_populate_soc_caps':
  CC      drivers/staging/qcacld-3.0/core/dp/txrx/ol_txrx_ipa.o
/home/matheus/derp/kernel/oneplus/sm8150/drivers/staging/qcacld-3.0/core/wma/src/wma_main.c:6315:21: error: the comparison will always evaluate as 'true' for the pointer operand in 'mac_phy_cap + (sizetype)((long unsigned int)i * 244)' must not be NULL [-Werror=address]
 6315 |                 if (&mac_phy_cap[i]) {
      |

Signed-off-by: Cyber Knight <cyberknight755@gmail.com>
Change-Id: Ifb64af14f7bd6215682c5fb73e77ead250890337
Signed-off-by: TogoFire <togofire@mailfence.com>
(cherry picked from commit 2b21f302245bdaeb0d5bb591bf24f2ad00b47bf7)
Signed-off-by: Madara273 <ravenhoxs@gmail.com>
Signed-off-by: Robin <hanya8493@gmail.com>